=== MartyBurns/cpsframework/sandbox/test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- W3C Schema generated by XMLSpy v2016 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="name" type="name"/>
	<xs:element name="actor" type="actor"/>
	<xs:element name="timing" type="timing"/>
	<xs:element name="tracing" type="xs:string"/>
	<xs:element name="concerns" type="concerns"/>
	<xs:element name="property" type="xs:string"/>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="Synchronization" type="Synchronization"/>
	<xs:element name="IntervalAndLatencyControl" type="xs:string"/>
	<xs:complexType name="actor">
		<xs:sequence>
			<xs:element ref="name"/>
			<xs:element ref="description"/>
			<xs:element ref="concerns"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="timing">
		<xs:sequence>
			<xs:element ref="Synchronization"/>
			<xs:element ref="IntervalAndLatencyControl"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="concerns">
		<xs:sequence>
			<xs:element ref="timing"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Synchronization">
		<xs:sequence>
			<xs:element ref="property"/>
			<xs:element ref="tracing"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="name">
		<xs:restriction base="xs:string">
			<xs:enumeration value="clock"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== MartyBurns/cpsframework/sandbox/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<actor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/_Project/NIST/Source/github/cpsframework/test.xsd">
	<name>clock</name>
	<description>A time keeping device</description>
	<concerns>
		<timing>
			<Synchronization>
				<property>clock can receive time sync from gps system</property>
				<tracing>/a/b/c/d</tracing>
			</Synchronization>
			<IntervalAndLatencyControl>clock drifts by less than 1 second per day</IntervalAndLatencyControl>
		</timing>
	</concerns>
</actor>
